{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "contract-negotiation-store-cosmos",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "contract-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "azure-cosmos-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 27481,
          "sha512": "2a800bad37f474c0dbe9f0400bb62180298455b2a4dc1ba5ef3ba34c4601610a763f0b3622a41ff6ffa74160222dedd0f3091f5863aea926b07ded84068dfa0e",
          "sha256": "2478366e6a0760620f4916029a707d3217002d857e8ce03282221d4d3a614532",
          "sha1": "77a7089b1781f23e69a616195d08e885a6332982",
          "md5": "78fc272be27340c31bbbf0a442760663"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.azure",
          "module": "azure-cosmos",
          "version": {
            "requires": "4.37.0"
          }
        },
        {
          "group": "dev.failsafe",
          "module": "failsafe",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "azure-cosmos-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 27481,
          "sha512": "2a800bad37f474c0dbe9f0400bb62180298455b2a4dc1ba5ef3ba34c4601610a763f0b3622a41ff6ffa74160222dedd0f3091f5863aea926b07ded84068dfa0e",
          "sha256": "2478366e6a0760620f4916029a707d3217002d857e8ce03282221d4d3a614532",
          "sha1": "77a7089b1781f23e69a616195d08e885a6332982",
          "md5": "78fc272be27340c31bbbf0a442760663"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "b1900cb358b1e5603f58eb66e272780cfa71f78d2ddab14b5cecc6f0d06cf1b21edbda17360e944d21bed2ec8548468d329c9d3509bd2bc6498ed659ec8efdc7",
          "sha256": "716771fa9cd8bad32205a4ac44797c1c724fbd51fd1f4999fa85c445a1f129a7",
          "sha1": "a7d8ec2dad96a2079b75949525c2f621f704e531",
          "md5": "66a1d0d71efeb5ec991378c39ad1d458"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "contract-negotiation-store-cosmos-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 7871,
          "sha512": "543e1e3544ec5619c56a9b10ab725d0ed5775a528459efdd435092d76a92442af58241b5ac70b90b0c50ccfaa205ae556fcbf72f4682b6e74f37247443fceccb",
          "sha256": "8e2e91ee2ea52a255319fca8b130003bc6e8d67ee39e11d7612d0a6de4976260",
          "sha1": "d4b43a654be46faa277a47c3e83610eaa577c367",
          "md5": "615d92f348dad206e33682c087f03234"
        }
      ]
    }
  ]
}
