{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "contract-negotiation-api",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 39134,
          "sha512": "8eae7da807f274d8f8c20609279ae334edd567fa953539e19f4e12b05966920e79c4c9c4fbc774fb5baa5a7b783b95a67a895d914f070f02604dfd6697c40515",
          "sha256": "66e418505fb0e90393a5bc656026a1d41cebe44e981a635481aed54ef98df4f4",
          "sha1": "d69fb27a9c32a3033d18e090ea757941c0743ef3",
          "md5": "3d1a35fdb753a2f0e77ff11acd69ae90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "api-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "management-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-jaxrs2-jakarta",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 39134,
          "sha512": "8eae7da807f274d8f8c20609279ae334edd567fa953539e19f4e12b05966920e79c4c9c4fbc774fb5baa5a7b783b95a67a895d914f070f02604dfd6697c40515",
          "sha256": "66e418505fb0e90393a5bc656026a1d41cebe44e981a635481aed54ef98df4f4",
          "sha1": "d69fb27a9c32a3033d18e090ea757941c0743ef3",
          "md5": "3d1a35fdb753a2f0e77ff11acd69ae90"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "976396ec7062f5bd0cf26796fedadee0fe8aa23bf6ca6fbee9f931e907fedd3b238f545c043479e29118df8d6de39ac71d7d467b12e500255515e63548316f27",
          "sha256": "37c9caca62bb0e1cbddb538e2cdba28849a492283afbccebe9ee0b5579e2edb4",
          "sha1": "fb229210827dad98cb9e964a02b8e615bce5a4e5",
          "md5": "56779ed9682ac72b3f3153ce355af74d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "contract-negotiation-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 15488,
          "sha512": "d382d275ad08e2381435c9e4346252c91df64345c58eee407562e8aa5c26f6aa5b5cb3619dafb5ff57ccecbc187be1258613bf39523d9f4105872a41ecee2bbd",
          "sha256": "e8955ea8f90ee258ba88d67604bf4c1bd6212894b2a3f67c17fe2e5b04e8d813",
          "sha1": "fa6aca75775a5fc46888b9995b82b7d144af5e2f",
          "md5": "b7cd7f075d82b8eabd25cf3e558a2518"
        }
      ]
    }
  ]
}
