{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "runtime-metamodel",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metamodel-0.0.1-SNAPSHOT.jar",
          "url": "runtime-metamodel-0.0.1-SNAPSHOT.jar",
          "size": 29612,
          "sha512": "49f0f7adfc680f3a53c138fc3c45d00075d0bb9d258ab43a11a0941b34cebc0e8398c1570fcedbc964327d4058b499c249c3865a4ff40a0ff7306e10a259d5e4",
          "sha256": "27229b1330231fa179de134572c192cb92a178c6af767518d147679bcbf094e9",
          "sha1": "46b96380672fc2c060086af01386e332cbaa4938",
          "md5": "e89f90f93d21eea81df22a2b6d8debeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metamodel-0.0.1-SNAPSHOT.jar",
          "url": "runtime-metamodel-0.0.1-SNAPSHOT.jar",
          "size": 29612,
          "sha512": "49f0f7adfc680f3a53c138fc3c45d00075d0bb9d258ab43a11a0941b34cebc0e8398c1570fcedbc964327d4058b499c249c3865a4ff40a0ff7306e10a259d5e4",
          "sha256": "27229b1330231fa179de134572c192cb92a178c6af767518d147679bcbf094e9",
          "sha1": "46b96380672fc2c060086af01386e332cbaa4938",
          "md5": "e89f90f93d21eea81df22a2b6d8debeb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-metamodel-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "runtime-metamodel-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 352540,
          "sha512": "c268aa89dd4119fdac8ca27e74d2bd0ffc849f9c36a0aace377d58530068cfcfc3516f4ca69274d3de91e5c6425d988aeaecdaccb44f3fbd6fbd7b5ea93be71a",
          "sha256": "4086fb914d1966a8da53ba5107c0ca70331eb9dd687821f0ed740683f37e8881",
          "sha1": "50e2060805e879927810463710848d83642db028",
          "md5": "633b6e8a8826aaeacf2b009a6de4b47b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-metamodel-0.0.1-SNAPSHOT-sources.jar",
          "url": "runtime-metamodel-0.0.1-SNAPSHOT-sources.jar",
          "size": 22620,
          "sha512": "84ff1267c7570ad63d901ceb48120cac1e789fcb6a0feef524f322ff54e9eb4d3913a1c19794c08ef44aa612a506bdeb59f68fc558a3f28252a41a44d58ff62c",
          "sha256": "3c0939fd688cd8fd31bded475409bf56a3413ede82d92ef2bc787beaf15f3d8f",
          "sha1": "68e554a71e68d49bf2db35f46a32a8e37a46e320",
          "md5": "0303fb843cd81dce0bd8268294e09e17"
        }
      ]
    }
  ]
}
