{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "transform-spi",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "core-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 21102,
          "sha512": "1317999fce61f4505a3b25e582945efeac54e3822fc5ae1edced9b614cac2fb10dd42b6071959dcebb3ee0bea5bc00978d2b88557e422a4a83ef097647e8806b",
          "sha256": "d2841a1fa5de1abfaa0531b664bbe2c18782cc8696ad302d4bc0f20cbce52907",
          "sha1": "8c8aa8af1d5396ec5ec18c70ea98eb6cbf5f1dfd",
          "md5": "d4fee1c17a83748dc8c07ed361b9c619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "core-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 21102,
          "sha512": "1317999fce61f4505a3b25e582945efeac54e3822fc5ae1edced9b614cac2fb10dd42b6071959dcebb3ee0bea5bc00978d2b88557e422a4a83ef097647e8806b",
          "sha256": "d2841a1fa5de1abfaa0531b664bbe2c18782cc8696ad302d4bc0f20cbce52907",
          "sha1": "8c8aa8af1d5396ec5ec18c70ea98eb6cbf5f1dfd",
          "md5": "d4fee1c17a83748dc8c07ed361b9c619"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "f20552ebb48bdff845a8d07def4c42da24544fcfdcb61734563a2c30fae19f5d484ad4d448a4b1a044e4ab4be3e88d4e9bb16f49865abb5b2710fe4e89dfb524",
          "sha256": "abb383f89ba767431e66f2ace30f6976eabf1e4c8d36a80973dfbbc0fab20d0f",
          "sha1": "b446b721d7c24dd993b8d565a58955b5c6969896",
          "md5": "ab0d2d968e0c79a7dc692640d07ef247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "transform-spi-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 5126,
          "sha512": "09c290fb631908a08df85615cd9072bb0eb5a831478e377aa2d04eb36f06fca3ad56717e30b7dd0e3af8b0b478b74458be5e36f99950665c674ec5516c2cb081",
          "sha256": "72a7dc492836c824f3a4597a7d78ac49ec000cb7d62ff2b3d3f0cd191ca7bc94",
          "sha1": "eb4288514e1c99cda3dbf642a98020f0b48d5349",
          "md5": "57967bb68c9023469ef302d2cc3bdf03"
        }
      ]
    }
  ]
}
