{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "transfer-process-api",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "transfer-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 38553,
          "sha512": "dec27a3c4f66986b987ffc3a0298a2d74877537311d8a227d077e332c74133af8cfdc49703065d2a2a4ad1cadfbe51c1363f4a45d958846193ecb07416e88ad5",
          "sha256": "7239fd8bcd09010d1de99a72acc5bb93b8c3a398fa92601a3916ca684b69e807",
          "sha1": "144fc315bdddad66822832b9f4475b713f7a426c",
          "md5": "7be531461ae075096c010ecbdef69ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "api-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "management-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-jaxrs2-jakarta",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "transfer-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 38553,
          "sha512": "dec27a3c4f66986b987ffc3a0298a2d74877537311d8a227d077e332c74133af8cfdc49703065d2a2a4ad1cadfbe51c1363f4a45d958846193ecb07416e88ad5",
          "sha256": "7239fd8bcd09010d1de99a72acc5bb93b8c3a398fa92601a3916ca684b69e807",
          "sha1": "144fc315bdddad66822832b9f4475b713f7a426c",
          "md5": "7be531461ae075096c010ecbdef69ec8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "3fa218a8e9b29b6dcb1b53227d2c241c872f45909be1718667c8e8dc2b18f6d09274aa92e99524b7c74be0bc3e103682fbe598ba70b9ade582c8500800ac4a93",
          "sha256": "726a65baaa934b37ec1cbd7f665cc37e4bb17c1b7f80d90359e8edbfdbefe5dc",
          "sha1": "c741f09e78965497ad4dded287c8621d3770e7c2",
          "md5": "9ee905b429d2d98b713f61fd10364c66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "transfer-process-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 14659,
          "sha512": "ada2a15bb03cea9c5b0e90acfe10528fcf363ae78c4116860f95cb2c19a472139c06497937d1f9b26171214f5b99fca915079a90993a53a05895a8a07aa80100",
          "sha256": "a85d2c41ac77e05ebb0841c766f92de78ee98f29ca101ddb29b2d8150dc6f79d",
          "sha1": "e53ccdf94ecf7909257f7055c8fb0141f528e0aa",
          "md5": "ec13f4b2c67c0aef2cf23c2eecced021"
        }
      ]
    }
  ]
}
