{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "transaction-atomikos",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "core-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-datasource-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 37103,
          "sha512": "91bf0b0a7a16443dc386fd6d7d28c82670656fc80494c7a5daf6821fd207241e6a9786643cdff22c454b7ca5b50b5fd502c458d0a0a263e0ff6f72bd86d0d04d",
          "sha256": "6d42424868b5e3afa2ba3486e7e7179821c229f659d3239275d525e7cc0884f7",
          "sha1": "7a42b279431719019aba54049770ae25a4807d34",
          "md5": "2db7069157e3fdafe871a3b596f16fad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "javax.transaction",
          "module": "javax.transaction-api",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.atomikos",
          "module": "transactions-jta",
          "version": {
            "requires": "5.0.8"
          }
        },
        {
          "group": "com.atomikos",
          "module": "transactions-jdbc",
          "version": {
            "requires": "5.0.8"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "core-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transaction-datasource-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 37103,
          "sha512": "91bf0b0a7a16443dc386fd6d7d28c82670656fc80494c7a5daf6821fd207241e6a9786643cdff22c454b7ca5b50b5fd502c458d0a0a263e0ff6f72bd86d0d04d",
          "sha256": "6d42424868b5e3afa2ba3486e7e7179821c229f659d3239275d525e7cc0884f7",
          "sha1": "7a42b279431719019aba54049770ae25a4807d34",
          "md5": "2db7069157e3fdafe871a3b596f16fad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "54488300f5c790a9b0862130d70e0c48e44a170736d9103bbe11fa132abd05bda65945eecaf52b239ffc93e4af05abea411494cfe6c36ee870a43f172d6673ef",
          "sha256": "ad3016ee81146b3511e58c1acbe5a0433bf35ec810b7c94d8cf90e9e2930f456",
          "sha1": "f487ba9a4fee7ee4f30629b9996f2768032d36cb",
          "md5": "d43b02515c5a162495b96dfe619e231a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "transaction-atomikos-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 13457,
          "sha512": "1dd0d14f9d88952bf63b070c770b14ea020c5cd2474a4a0863f2270bd2c87e739e8e13b9573e6f6bda4854038732fc33bb6406b7283a89a1e8b147d635dea649",
          "sha256": "2f9c7974f074e5a929a15f01cc41ed4b020a23c5002971a228b3363d4810255e",
          "sha1": "0321c8161a551c6542a09a7a3df21f0fba9249e3",
          "md5": "e936c92634c4e6a6611294fd6defd6b4"
        }
      ]
    }
  ]
}
