{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "ids-api-multipart-endpoint-v1",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "ids-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-transform-v1",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "http",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 56595,
          "sha512": "ef4e4bcaf2ce19bd70f7beeb0e49b290cac6ce5cc5c1bc8dc0a45ff96cbd97c576e362c58196f79d912a6658b83fb25441a4a66fdf5606336f26d4ba7971e341",
          "sha256": "adaaf2c490071d8e84a0857fc2203519e3769bb7a1e0c42a55bb22e8310bb275",
          "sha1": "5f6930bc6b4f9807b94e6c764c1b0d7799de2764",
          "md5": "df085f29799472c3036d885d517da41f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "ids-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.glassfish.jersey.media",
          "module": "jersey-media-multipart",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-transform-v1",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "http",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 56595,
          "sha512": "ef4e4bcaf2ce19bd70f7beeb0e49b290cac6ce5cc5c1bc8dc0a45ff96cbd97c576e362c58196f79d912a6658b83fb25441a4a66fdf5606336f26d4ba7971e341",
          "sha256": "adaaf2c490071d8e84a0857fc2203519e3769bb7a1e0c42a55bb22e8310bb275",
          "sha1": "5f6930bc6b4f9807b94e6c764c1b0d7799de2764",
          "md5": "df085f29799472c3036d885d517da41f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 350931,
          "sha512": "cd690e1b40293160b5951f785b3d44c044fc4f327875592b3df4cb92a77eaa9b588b338f5984ed1cca6f159f6580a9d285abffc500057ec29dbad8b6c2cbe1f4",
          "sha256": "cfbc396fb19b47d23e804f3a4c2acc9e6b0a0698d97f7a16018c1999bf3194f8",
          "sha1": "f5e13b94f362a1bd9c2c13147a7e0cfb0840d2ba",
          "md5": "e73c6275e9e5ee5fe99fab0d79aa807f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "ids-api-multipart-endpoint-v1-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 23576,
          "sha512": "7ed29e08dad6604f05623b45f363e1dc74a10733800b12ee6464a8920ce0a94920e96d68cae8c9504eb0f838890501cf0cba8189c8b190d9066ca4dcd49b3d19",
          "sha256": "c89bcae1258c78c5ce6b2b67b385dcb631ec91b52183d7460f218e339a2428a0",
          "sha1": "b9f73fa7754ce18340f595894c5acf2aac5c905d",
          "md5": "d552fe05619562ee6beb7b3160b824b2"
        }
      ]
    }
  ]
}
