{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "module-names",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "module-names-0.0.1-SNAPSHOT.jar",
          "url": "module-names-0.0.1-SNAPSHOT.jar",
          "size": 15697,
          "sha512": "354ae3360e58b0e46c92908cb71ea25fe6c18eecb0035b9da0a32e4e46b9063019111440dc3397b56a259f130fc278ee93666aa670684c9bbf6baa5bd15ce746",
          "sha256": "cab2626b1e1461900ada514c3c5fd2a768147f9fbbd1e0da51da1fe25fe32e2c",
          "sha1": "eec2ca10d73ed2b5e85aedb5b4b9b5505d45189e",
          "md5": "7603cb9da89e12034dc0dd34ec950b9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "module-names-0.0.1-SNAPSHOT.jar",
          "url": "module-names-0.0.1-SNAPSHOT.jar",
          "size": 15697,
          "sha512": "354ae3360e58b0e46c92908cb71ea25fe6c18eecb0035b9da0a32e4e46b9063019111440dc3397b56a259f130fc278ee93666aa670684c9bbf6baa5bd15ce746",
          "sha256": "cab2626b1e1461900ada514c3c5fd2a768147f9fbbd1e0da51da1fe25fe32e2c",
          "sha1": "eec2ca10d73ed2b5e85aedb5b4b9b5505d45189e",
          "md5": "7603cb9da89e12034dc0dd34ec950b9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "module-names-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "module-names-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 290819,
          "sha512": "cef11f905399471422aceac2e2eaca35a9e965a1354cf067a7ab9a0b5812471f89655f65cc8219eb13ba97e014b675a45fa5945b71a752623c585fefb2345570",
          "sha256": "85abe1cabfef106debdb249e1063434ac3b63532412a378dba558314729a3d74",
          "sha1": "f52239a8e84659d747118e59c8687cbf7d88dd3c",
          "md5": "31afc474e04b9b70418b44af55e70709"
        },
        {
          "name": "module-names-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "module-names-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 290819,
          "sha512": "cef11f905399471422aceac2e2eaca35a9e965a1354cf067a7ab9a0b5812471f89655f65cc8219eb13ba97e014b675a45fa5945b71a752623c585fefb2345570",
          "sha256": "85abe1cabfef106debdb249e1063434ac3b63532412a378dba558314729a3d74",
          "sha1": "f52239a8e84659d747118e59c8687cbf7d88dd3c",
          "md5": "31afc474e04b9b70418b44af55e70709"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "module-names-0.0.1-SNAPSHOT-sources.jar",
          "url": "module-names-0.0.1-SNAPSHOT-sources.jar",
          "size": 8374,
          "sha512": "96562270da711a4adfd0a613be15e6f49cae949397a03302222c3333945c5cc132ed3083a233bd4d203e95b58d96c4d59c4288f00320ed34eee682bdbe56273d",
          "sha256": "a58ae65c7e733d2e98d36fb2bea6e6ba3171fe25a46fa0286558b6aa88de3f7a",
          "sha1": "33fc13c2f3cd5b2de87fc74a352aa7a794147b38",
          "md5": "7e942c4de2243916c152db905c960cea"
        },
        {
          "name": "module-names-0.0.1-SNAPSHOT-sources.jar",
          "url": "module-names-0.0.1-SNAPSHOT-sources.jar",
          "size": 8374,
          "sha512": "96562270da711a4adfd0a613be15e6f49cae949397a03302222c3333945c5cc132ed3083a233bd4d203e95b58d96c4d59c4288f00320ed34eee682bdbe56273d",
          "sha256": "a58ae65c7e733d2e98d36fb2bea6e6ba3171fe25a46fa0286558b6aa88de3f7a",
          "sha1": "33fc13c2f3cd5b2de87fc74a352aa7a794147b38",
          "md5": "7e942c4de2243916c152db905c960cea"
        }
      ]
    }
  ]
}
