{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "data-plane-selector-core",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-selector-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "connector-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "boot",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 25431,
          "sha512": "27061cec88412ff8afc4261d1e5486f85554b6d19a173f41c20d9de2edfb625fea77c6494703093c5f65368d125e51d82c2f28882be008ff55cc895e235fc58d",
          "sha256": "756835f614caa7952d8d9184113f2fb4d58a6671652ca284ca4f83b826baa884",
          "sha1": "474272c2974df2cf1ee4ef2f4f6a335ed3c78725",
          "md5": "b8f77b9bc21b1c9a63b9db7bc3d6e53d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-selector-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "connector-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "boot",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 25431,
          "sha512": "27061cec88412ff8afc4261d1e5486f85554b6d19a173f41c20d9de2edfb625fea77c6494703093c5f65368d125e51d82c2f28882be008ff55cc895e235fc58d",
          "sha256": "756835f614caa7952d8d9184113f2fb4d58a6671652ca284ca4f83b826baa884",
          "sha1": "474272c2974df2cf1ee4ef2f4f6a335ed3c78725",
          "md5": "b8f77b9bc21b1c9a63b9db7bc3d6e53d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 312266,
          "sha512": "709222b5244b9cb41e43af3edc87e44fad2af78ea23ec5e0d971d9ea7dae4fb34a8b769deec1c3f76fca2d5255eaf38d9606443ade168f54eed3dcfd89dcb93b",
          "sha256": "dbe297f207c4144b3a294f1c23d567e84da772d4ff84f458eab3d091997ae432",
          "sha1": "27eb0eab1e01c9c28de530a3a6f4b4bbe1f76c64",
          "md5": "046f2e3a4d121703e79118039fe71029"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "data-plane-selector-core-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 7527,
          "sha512": "f76c0806fb7773e7163c9b2f61134443704f975941c50ae7aa692c7bdbf1aa7713242927e47616c48f7934699d0763985b34622397acfcc21caf2cfcddd5e788",
          "sha256": "4df44fb67445e962779a8cdb1d5386d2f9eea8210a835b8c299569cb693a9567",
          "sha1": "c9512ba0969d533e0f6009ab882be7df790c44f8",
          "md5": "21d5b63400f98d2a3a9b663423c70b4c"
        }
      ]
    }
  ]
}
