{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "data-plane-core",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "web-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "connector-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "boot",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "http",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-framework",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "61a86119c5594b12fce4d43adc12b45f9a4e461c2abeb2b9eddaf8574cd60d00bae178f7fbc7f53180f3c4fcde4c3b311889383bcd307bb5c54877f766c413e2",
          "sha256": "6957664f878c43c85b5de639162922f7eafa5b7ea0c53eac632380964e3fbc1d",
          "sha1": "bd412e2b208a321d286402c447b364d4c689e86a",
          "md5": "2dcd4366083da4cf55741ff911dee54d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "web-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "connector-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "boot",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "http",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-framework",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "61a86119c5594b12fce4d43adc12b45f9a4e461c2abeb2b9eddaf8574cd60d00bae178f7fbc7f53180f3c4fcde4c3b311889383bcd307bb5c54877f766c413e2",
          "sha256": "6957664f878c43c85b5de639162922f7eafa5b7ea0c53eac632380964e3fbc1d",
          "sha1": "bd412e2b208a321d286402c447b364d4c689e86a",
          "md5": "2dcd4366083da4cf55741ff911dee54d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "394c941682d70c1dcfe6c449c1eae36f36ec1de73d450e3cbd3206c596f3ce9db7685bb80200a503a540e8cb9f302506cf3e6106ac93c5b26fab0feb7e46b851",
          "sha256": "f4eeded1bec209b6f5a9f5f3951a2668dde9a5f775536706037bf7077c0a0eb8",
          "sha1": "686162eaff9cdfbb7d8e35acdda7eb0f45da3544",
          "md5": "5a20cf05e8ae64ade52b3bdb4ce25c09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "data-plane-core-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "394c941682d70c1dcfe6c449c1eae36f36ec1de73d450e3cbd3206c596f3ce9db7685bb80200a503a540e8cb9f302506cf3e6106ac93c5b26fab0feb7e46b851",
          "sha256": "f4eeded1bec209b6f5a9f5f3951a2668dde9a5f775536706037bf7077c0a0eb8",
          "sha1": "686162eaff9cdfbb7d8e35acdda7eb0f45da3544",
          "md5": "5a20cf05e8ae64ade52b3bdb4ce25c09"
        }
      ]
    }
  ]
}
