{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "management-api",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "api-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "management-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "asset-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "catalog-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-agreement-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-definition-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-negotiation-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "policy-definition-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transfer-process-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "management-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "management-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "a596368581b2970c5b00f27a8be140199c746ae6ecd8884fd02ce56321546d73b15b1ca628f8520226a06ea54c8bcb25ad896ea8651271914311338d912843e7",
          "sha256": "628a9ea4519b002c44ea1ebb74a8b3a4fa4492c1113a31cd20cd4f7ae28c6993",
          "sha1": "81d11898a4a9532fe1f726fea3d3084bfbcb4875",
          "md5": "35fd1cf8e4e286f856403f6c2ac6f760"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "api-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "management-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "asset-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "catalog-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-agreement-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-definition-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "contract-negotiation-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "policy-definition-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "transfer-process-api",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "management-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "management-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "a596368581b2970c5b00f27a8be140199c746ae6ecd8884fd02ce56321546d73b15b1ca628f8520226a06ea54c8bcb25ad896ea8651271914311338d912843e7",
          "sha256": "628a9ea4519b002c44ea1ebb74a8b3a4fa4492c1113a31cd20cd4f7ae28c6993",
          "sha1": "81d11898a4a9532fe1f726fea3d3084bfbcb4875",
          "md5": "35fd1cf8e4e286f856403f6c2ac6f760"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "management-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "management-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "db1797a411ff83b7b24afc06b8e99c64ecec260d8bcde3d5dfd901510122950694edf4080a2e03d507ca626a853e631ac615dc3becb9d3f386d913dabd164bf1",
          "sha256": "bfa4a7c0b5170ecfba22549e2b5aae868680f1e198f367632124d618a6174ca1",
          "sha1": "f9248b89c546a694137a0f7c7d7f5db74da04fc9",
          "md5": "0a6ee34e4bf8bae72fbc9b40c27c599a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "management-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "management-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "db1797a411ff83b7b24afc06b8e99c64ecec260d8bcde3d5dfd901510122950694edf4080a2e03d507ca626a853e631ac615dc3becb9d3f386d913dabd164bf1",
          "sha256": "bfa4a7c0b5170ecfba22549e2b5aae868680f1e198f367632124d618a6174ca1",
          "sha1": "f9248b89c546a694137a0f7c7d7f5db74da04fc9",
          "md5": "0a6ee34e4bf8bae72fbc9b40c27c599a"
        }
      ]
    }
  ]
}
