{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "ids-token-validation",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "oauth2-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "jwt-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "de.fraunhofer.iais.eis.ids.infomodel",
          "module": "java",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 20165,
          "sha512": "e2a1134a889b6ecd339c36ef0b8c473447a1d55c46ae5b971574f89d20fe6106a4bf58ebb86abd005271bff6cce0c69853dd0302873f3be583a98fdc1017893a",
          "sha256": "89f9820d3679a07e471fe116896548d898eb8321243f813cd0aac36f8a492812",
          "sha1": "992bedd6403eb6471ca897b7366b36e6234c0b3a",
          "md5": "8e2e1657e51dab0a5da1f1983b0e9ed2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "control-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "ids-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "oauth2-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "jwt-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "de.fraunhofer.iais.eis.ids.infomodel",
          "module": "java",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 20165,
          "sha512": "e2a1134a889b6ecd339c36ef0b8c473447a1d55c46ae5b971574f89d20fe6106a4bf58ebb86abd005271bff6cce0c69853dd0302873f3be583a98fdc1017893a",
          "sha256": "89f9820d3679a07e471fe116896548d898eb8321243f813cd0aac36f8a492812",
          "sha1": "992bedd6403eb6471ca897b7366b36e6234c0b3a",
          "md5": "8e2e1657e51dab0a5da1f1983b0e9ed2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 292429,
          "sha512": "d5039bac1c823b8b92edf4e3e5e6fab8ed2a34ec905badb675002b1f67875f7ad0564bf05bfe5f866dfe721dcdc2a0471349bf55e4c028993bf598a95885eb43",
          "sha256": "7006ac0e609641c41211eaa09481f85528a11f7afddaca7e7fd5e1bf2b02a5d4",
          "sha1": "ecaec42eb0c5a59e3417259a07188f298000b12b",
          "md5": "6520566b06d7824248a6ee2fffa77707"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "ids-token-validation-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 4162,
          "sha512": "50d7a1fa7bf9c880f5df5fe65969e67571e3b1171ce84cb72cda5d2b564e2f5ff377a68c91dac54d01850b52e3aee3c866f2727d04a6ca8975e56b847ee78362",
          "sha256": "a9e16fb72e1f4980abe24934174473edd7fb1ebf8e7960582721caf2b207f494",
          "sha1": "0c28277d2b44d736115c5c97d776ad6588f96975",
          "md5": "985d1f95b2437ec6cc3453957c2e6eed"
        }
      ]
    }
  ]
}
