{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "data-plane-api",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "http-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "web-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 35522,
          "sha512": "182f9c98de2a8e7e151ea1f869160b41b062484e871e6f4982b8bd0dc180c95de94a9820f0bcb57248bc14abbd7d01ec43e1a3dcc904f8688620c29b5ae1765d",
          "sha256": "888b47d5f7a4b30b5b5748b4342e1c1107dbfdded3f1a2f15d89df33ba0aa86d",
          "sha1": "1930eb1bfccdc1897bf1889fa9aed812a0c2a067",
          "md5": "5de26ef387aec2ffbc55bdb9205fa390"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-util",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "control-api-configuration",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-jaxrs2-jakarta",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "jakarta.ws.rs",
          "module": "jakarta.ws.rs-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "http-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "web-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "data-plane-spi",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.jaxrs",
              "module": "jackson-jaxrs-json-provider"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 35522,
          "sha512": "182f9c98de2a8e7e151ea1f869160b41b062484e871e6f4982b8bd0dc180c95de94a9820f0bcb57248bc14abbd7d01ec43e1a3dcc904f8688620c29b5ae1765d",
          "sha256": "888b47d5f7a4b30b5b5748b4342e1c1107dbfdded3f1a2f15d89df33ba0aa86d",
          "sha1": "1930eb1bfccdc1897bf1889fa9aed812a0c2a067",
          "md5": "5de26ef387aec2ffbc55bdb9205fa390"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 326439,
          "sha512": "728b5472595e4dc626769fcc8f526c396da85632a6f6908ebbc81ae973016e6da495c99e4e41a1bd21b6f1c3f49080c8733da4d3e54aa51838d9bb9ce8b04a8c",
          "sha256": "a82f330663df1dcdf962ea777e01fcfb1edcf30d09511502066afe8f0fcc50d9",
          "sha1": "09401988da732686441ffb9e96481500a8eaf586",
          "md5": "1070e0132eeb577c78ee65e8baef8fe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "data-plane-api-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 14493,
          "sha512": "149d418525c435b6ad227c0d037f370d0e4c5a23022b0fc7f1e4ca7fafb552339363813ef20b82d2ce2d231a6bfd75fba763f4740d66e58f4eba623e5db45d01",
          "sha256": "e974ed2899f3297aa4c554acfa943073e87af9da197a3b48644fc23a198d056a",
          "sha1": "1982a8c67f93120ea02abed39ded4a34aac83861",
          "md5": "56f43b49247fdc4f65ebfe503a7fa54f"
        }
      ]
    }
  ]
}
