{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "edc-build",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "edc-build-0.0.1-SNAPSHOT.jar",
          "url": "edc-build-0.0.1-SNAPSHOT.jar",
          "size": 58057,
          "sha512": "7970f169a8de03e9b0e2bfe1c7e63a6b2ec00d822b6e17cc4feb7065b3c7125ce33ecd024b2e589490781c366a0d2ad70f693907cb16210f2aad4f64bd4b019d",
          "sha256": "3576952c82f029886bc94ac60d3dd5eb1d91285daa4d9e5d969119e79aacaf85",
          "sha1": "6dc5a85d52e115c060be17ca6173547dfe3c9f80",
          "md5": "b5294bca7767f953a8890addf061dc35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "autodoc-plugin",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "test-summary",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "module-names",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "openapi-merger",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.autonomousapps",
          "module": "dependency-analysis-gradle-plugin",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "gradle.plugin.org.gradle.crypto",
          "module": "checksum",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "gradle.plugin.org.hidetake",
          "module": "gradle-swagger-generator-plugin",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "io.swagger.core.v3",
          "module": "swagger-gradle-plugin",
          "version": {
            "requires": "2.2.7"
          }
        },
        {
          "group": "com.rameshkp",
          "module": "openapi-merger-gradle-plugin",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "edc-build-0.0.1-SNAPSHOT.jar",
          "url": "edc-build-0.0.1-SNAPSHOT.jar",
          "size": 58057,
          "sha512": "7970f169a8de03e9b0e2bfe1c7e63a6b2ec00d822b6e17cc4feb7065b3c7125ce33ecd024b2e589490781c366a0d2ad70f693907cb16210f2aad4f64bd4b019d",
          "sha256": "3576952c82f029886bc94ac60d3dd5eb1d91285daa4d9e5d969119e79aacaf85",
          "sha1": "6dc5a85d52e115c060be17ca6173547dfe3c9f80",
          "md5": "b5294bca7767f953a8890addf061dc35"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "edc-build-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "edc-build-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 338194,
          "sha512": "7297664126e695812d8d67b281874f333d93d6b75d1c0f86284b944fd7caaf569894c9cbaf23be569d259c357064181febd11f6b7444d97a984dc1092178ba93",
          "sha256": "b7501a31c3bfdd77ca68001d5128d0dbfbdd600e67d275d787d82f5e12ac4ded",
          "sha1": "866fdbcc79b8166ee77df2a6ab35fe25caf7552b",
          "md5": "8ab527b83c238672fde993356786aea6"
        },
        {
          "name": "edc-build-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "edc-build-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 338194,
          "sha512": "7297664126e695812d8d67b281874f333d93d6b75d1c0f86284b944fd7caaf569894c9cbaf23be569d259c357064181febd11f6b7444d97a984dc1092178ba93",
          "sha256": "b7501a31c3bfdd77ca68001d5128d0dbfbdd600e67d275d787d82f5e12ac4ded",
          "sha1": "866fdbcc79b8166ee77df2a6ab35fe25caf7552b",
          "md5": "8ab527b83c238672fde993356786aea6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "edc-build-0.0.1-SNAPSHOT-sources.jar",
          "url": "edc-build-0.0.1-SNAPSHOT-sources.jar",
          "size": 34839,
          "sha512": "e346e88da5953e6e15ee058294e904acca9382ec3201f2209bfbf8c42a7161c92083148375752bfd434f9c520db768eb67f2a0e7023b32fc03a6dfbc6959801e",
          "sha256": "b302270b0b975eca817fcbd108c32f7106ec5e44d5b4f0be2ad3c5fb9a4741f0",
          "sha1": "b258f3df07514b69ff57990d16d76bcd87dd2244",
          "md5": "50004d623fc36be95c515caae2c6fd1b"
        },
        {
          "name": "edc-build-0.0.1-SNAPSHOT-sources.jar",
          "url": "edc-build-0.0.1-SNAPSHOT-sources.jar",
          "size": 34839,
          "sha512": "e346e88da5953e6e15ee058294e904acca9382ec3201f2209bfbf8c42a7161c92083148375752bfd434f9c520db768eb67f2a0e7023b32fc03a6dfbc6959801e",
          "sha256": "b302270b0b975eca817fcbd108c32f7106ec5e44d5b4f0be2ad3c5fb9a4741f0",
          "sha1": "b258f3df07514b69ff57990d16d76bcd87dd2244",
          "md5": "50004d623fc36be95c515caae2c6fd1b"
        }
      ]
    }
  ]
}
