{
  "formatVersion": "1.1",
  "component": {
    "group": "org.eclipse.edc",
    "module": "aws-s3-test",
    "version": "0.0.1-20230220.patch1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "718ca618b9834454f33cbd57ad7d4b2ac99d4f38de7c85fedb57807d528e8eec676896493b7b4f01a22cf399dbbfd803632088333ccd8b794a2dc59b20cd9fbf",
          "sha256": "7943889e90b3ec93896271f1d0e1fe71466c9e5160b407d61b194c903fac945e",
          "sha1": "b8acaa0279ba25ae8b081ecec5afacda83597c6e",
          "md5": "2972ec90a019a1f695d5967cf9401b57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "runtime-metamodel",
          "version": {
            "requires": "0.0.1-20230220-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT.jar",
          "size": 15548,
          "sha512": "718ca618b9834454f33cbd57ad7d4b2ac99d4f38de7c85fedb57807d528e8eec676896493b7b4f01a22cf399dbbfd803632088333ccd8b794a2dc59b20cd9fbf",
          "sha256": "7943889e90b3ec93896271f1d0e1fe71466c9e5160b407d61b194c903fac945e",
          "sha1": "b8acaa0279ba25ae8b081ecec5afacda83597c6e",
          "md5": "2972ec90a019a1f695d5967cf9401b57"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "aws-s3-test",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "junit",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.19.26"
          }
        }
      ],
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-test-fixtures.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-test-fixtures.jar",
          "size": 7383,
          "sha512": "d35c389f225ef740038de0581fc9a0198bf55ac66486b185cd2ea7de388fc600fd9b31a6f3289ed734de485bfd34e6d00a16d873aecd99781421febb0e3e5d2d",
          "sha256": "2cab08b0209cc26165b24ceff9d95bb37c24162358ab95576aa85c23ee4b29af",
          "sha1": "0223c8f2a27b223f20d7c2ad82a7fb4ef6d2e4fb",
          "md5": "14bc125f64195576723500f7653c38ab"
        }
      ],
      "capabilities": [
        {
          "group": "org.eclipse.edc",
          "name": "aws-s3-test-test-fixtures",
          "version": "0.0.1-20230220.patch1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.edc",
          "module": "aws-s3-core",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "aws-s3-test",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "org.eclipse.edc",
          "module": "junit",
          "version": {
            "requires": "0.0.1-20230220.patch1-SNAPSHOT"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.19.26"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-test-fixtures.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-test-fixtures.jar",
          "size": 7383,
          "sha512": "d35c389f225ef740038de0581fc9a0198bf55ac66486b185cd2ea7de388fc600fd9b31a6f3289ed734de485bfd34e6d00a16d873aecd99781421febb0e3e5d2d",
          "sha256": "2cab08b0209cc26165b24ceff9d95bb37c24162358ab95576aa85c23ee4b29af",
          "sha1": "0223c8f2a27b223f20d7c2ad82a7fb4ef6d2e4fb",
          "md5": "14bc125f64195576723500f7653c38ab"
        }
      ],
      "capabilities": [
        {
          "group": "org.eclipse.edc",
          "name": "aws-s3-test-test-fixtures",
          "version": "0.0.1-20230220.patch1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "2195db83014a5c7eb6527cdd19d866fbf8917782e846e12e778d7ab31fe7f0bbb94b01c2c25cbc9346aafe84e3f34163bff43c49aa224ba99ea038533ad24d92",
          "sha256": "e776777388f93cead48e9f7a20cb995f49a55fa0d9071d396b69cac961b4ad8f",
          "sha1": "be12cd70ad6ed61476441484af6f711cf938c860",
          "md5": "383a29bc1135f1f1a5f49ddf1f3621a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "url": "aws-s3-test-0.0.1-20230220.patch1-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "2195db83014a5c7eb6527cdd19d866fbf8917782e846e12e778d7ab31fe7f0bbb94b01c2c25cbc9346aafe84e3f34163bff43c49aa224ba99ea038533ad24d92",
          "sha256": "e776777388f93cead48e9f7a20cb995f49a55fa0d9071d396b69cac961b4ad8f",
          "sha1": "be12cd70ad6ed61476441484af6f711cf938c860",
          "md5": "383a29bc1135f1f1a5f49ddf1f3621a0"
        }
      ]
    }
  ]
}
